using AleTrack.Common.Enums;
using AleTrack.Common.Models;
using AleTrack.Common.Options;
using AleTrack.Entities;
using AleTrack.Features.OutgoingShipments.Commands.Update;
using AleTrack.Features.OutgoingShipments.Utils;
using AleTrack.Infrastructure.Persistence;
using AleTrack.Tests.Builders;
using AleTrack.Tests.Mocks;
using Moq;

namespace AleTrack.Tests.Features.OutgoingShipments;

/// <summary>
/// Fixtures shared across outgoing-shipment write tests: the company address every
/// write endpoint now depends on, a shipment arranged for a PUT, and a round-tripped
/// shipment/DTO pair for the content guard.
/// </summary>
internal static class OutgoingShipmentTestHelpers
{
    /// <summary>
    /// The company address configuration a write endpoint is constructed with — same
    /// values as the committed <c>appsettings.json</c> Company section.
    /// </summary>
    internal static readonly CompanyOptions Company = new()
    {
        Name = "AleTrack s.r.o.",
        StreetName = "Turistická",
        StreetNumber = "211",
        City = "Hrádek nad Nisou",
        Zip = "46334",
        Country = Country.Czechia,
        Latitude = 50.841437m,
        Longitude = 14.837309m
    };

    /// <summary>
    /// A shipment in the given state with one order stop, plus a PUT that round-trips
    /// it unchanged — so each test changes exactly the one thing it is about. Drivers are
    /// left empty: the default driver ID generated by <see cref="OutgoingShipmentBuilder.BuildUpdateDto"/>
    /// does not exist in this mock and is irrelevant to what these tests check.
    /// </summary>
    internal static (OutgoingShipment Shipment, UpdateOutgoingShipmentRequest Request, Mock<AleTrackDbContext> DbContext)
        Arrange(OutgoingShipmentState state, List<Brewery> breweries)
    {
        var shipmentId = Guid.NewGuid();
        var orderId = Guid.NewGuid();
        var client = ClientBuilder.BuildEntity(officialAddress: AddressBuilder.BuildEntity());
        var order = OrderBuilder.BuildEntity(publicId: orderId, client: client);

        var shipment = OutgoingShipmentBuilder.BuildEntity(publicId: shipmentId, state: state);
        shipment.Stops.Add(new OutgoingShipmentStop
        {
            Kind = OutgoingShipmentStopKind.Order,
            ClientOrder = order,
            Order = 1
        });

        var dbContext = AleTrackDbContextMockFactory.CreateMock(
            outgoingShipments: [shipment],
            orders: [order],
            breweries: breweries);
        dbContext.Setup(x => x.SaveChangesAsync(It.IsAny<CancellationToken>())).ReturnsAsync(1);

        var request = new UpdateOutgoingShipmentRequest
        {
            Id = shipmentId,
            Data = OutgoingShipmentBuilder.BuildUpdateDto(
                driverIds: [],
                clientOrderShipments: [new ClientOrderShipmentDto { ClientOrderId = orderId, Order = 1 }],
                state: state)
        };

        return (shipment, request, dbContext);
    }

    /// <summary>
    /// A Loaded shipment carrying two order stops (one with an item), a custom stop, two via
    /// points and a stock purchase — paired with a DTO describing exactly that content.
    /// </summary>
    internal static (OutgoingShipment Shipment, UpdateOutgoingShipmentDto Dto) RoundTripped()
    {
        var vehicle = VehicleBuilder.BuildEntity(publicId: Guid.NewGuid());
        var client = ClientBuilder.BuildEntity(officialAddress: AddressBuilder.BuildEntity());

        var place = new ClientDeliveryPlace
        {
            Id = 3,
            PublicId = Guid.NewGuid(),
            Name = "Letní zahrádka",
            Client = client,
            Address = AddressBuilder.BuildEntity()
        };

        var startBrewery = BreweryBuilder.BuildEntity(name: "Svijany");

        var product = ProductBuilder.BuildEntity(publicId: Guid.NewGuid());
        product.Id = 11;

        var order1 = OrderBuilder.BuildEntity(publicId: Guid.NewGuid(), client: client);
        var orderItem = new OrderItem
        {
            PublicId = Guid.NewGuid(),
            Product = product,
            ProductId = product.Id,
            Quantity = 6
        };
        order1.OrderItems = [orderItem];

        var order2 = OrderBuilder.BuildEntity(publicId: Guid.NewGuid(), client: client);

        var customStop = new OutgoingShipmentStop
        {
            PublicId = Guid.NewGuid(),
            Kind = OutgoingShipmentStopKind.Custom,
            Order = 3,
            Label = "Pumpa u dálnice",
            Note = "Tankování",
            Latitude = 49.5m,
            Longitude = 15.5m
        };

        var shipment = OutgoingShipmentBuilder.BuildEntity(
            publicId: Guid.NewGuid(),
            deliveryDate: DateTime.UtcNow.AddDays(1),
            state: OutgoingShipmentState.Loaded,
            vehicle: vehicle,
            stops:
            [
                new OutgoingShipmentStop
                {
                    PublicId = Guid.NewGuid(),
                    Kind = OutgoingShipmentStopKind.Order,
                    Order = 1,
                    ClientOrder = order1,
                    SelectedAddressKind = DeliveryAddressKind.DeliveryPlace,
                    ClientDeliveryPlace = place,
                    ClientDeliveryPlaceId = place.Id
                },
                new OutgoingShipmentStop
                {
                    PublicId = Guid.NewGuid(),
                    Kind = OutgoingShipmentStopKind.Order,
                    Order = 2,
                    ClientOrder = order2,
                    SelectedAddressKind = DeliveryAddressKind.Official
                },
                customStop
            ]);

        shipment.StartPointKind = ShipmentStartPointKind.Brewery;
        shipment.StartBrewery = startBrewery;

        shipment.RouteViaPoints =
        [
            new OutgoingShipmentRoutePoint { Order = 0, Latitude = 50.0m, Longitude = 14.0m },
            new OutgoingShipmentRoutePoint { Order = 1, Latitude = 50.5m, Longitude = 14.5m }
        ];

        shipment.StockPurchases =
        [
            new OutgoingShipmentStockPurchaseItem
            {
                PublicId = Guid.NewGuid(),
                Product = product,
                ProductId = product.Id,
                Quantity = 12
            }
        ];

        var dto = new UpdateOutgoingShipmentDto
        {
            Name = "Run",
            DeliveryDate = shipment.DeliveryDate,
            VehicleId = vehicle.PublicId,
            DriverIds = [],
            State = OutgoingShipmentState.Loaded,
            StartPointKind = ShipmentStartPointKind.Brewery,
            StartBreweryId = startBrewery.PublicId,
            ClientOrderShipments =
            [
                new ClientOrderShipmentDto
                {
                    ClientOrderId = order1.PublicId,
                    Order = 1,
                    SelectedAddressKind = DeliveryAddressKind.DeliveryPlace,
                    ClientDeliveryPlaceId = place.PublicId,
                    OrderItems = [new OrderItemInfoDto { OrderItemId = orderItem.PublicId }]
                },
                new ClientOrderShipmentDto
                {
                    ClientOrderId = order2.PublicId,
                    Order = 2,
                    SelectedAddressKind = DeliveryAddressKind.Official
                }
            ],
            CustomStops =
            [
                new CustomStopDto
                {
                    Id = customStop.PublicId,
                    Order = 3,
                    Label = "Pumpa u dálnice",
                    Note = "Tankování",
                    Latitude = 49.5m,
                    Longitude = 15.5m
                }
            ],
            RouteViaPoints =
            [
                new RoutePointDto { Latitude = 50.0m, Longitude = 14.0m },
                new RoutePointDto { Latitude = 50.5m, Longitude = 14.5m }
            ],
            StockPurchases =
            [
                new StockPurchaseDto
                {
                    Id = shipment.StockPurchases.First().PublicId,
                    ProductId = product.PublicId,
                    Quantity = 12
                }
            ]
        };

        return (shipment, dto);
    }
}
