using AleTrack.Common.Enums;
using AleTrack.Common.Models;
using AleTrack.Common.Utils;
using AleTrack.Entities;
using AleTrack.Features.OutgoingShipments.Commands.Update;
using AleTrack.Features.OutgoingShipments.Utils;
using AleTrack.Tests.Builders;
using AleTrack.Tests.Mocks;
using FluentAssertions;
using FluentValidation.TestHelper;
using Moq;

namespace AleTrack.Tests.Features.OutgoingShipments;

/// <summary>
/// Writing a start point: what persists, what is rejected, and when it freezes.
/// </summary>
public sealed class ShipmentStartPointWriteTests
{
    [Fact]
    public async Task HandleAsync_StartPointIsBrewery_PersistsTheBrewery()
    {
        var brewery = BreweryBuilder.BuildEntity(name: "Svijany");
        brewery.Id = 7;
        var (shipment, request, dbContext) = Arrange(OutgoingShipmentState.Created, [brewery]);

        request.Data.StartPointKind = ShipmentStartPointKind.Brewery;
        request.Data.StartBreweryId = brewery.PublicId;

        var endpoint = EndpointBuilder<UpdateOutgoingShipmentRequest, UpdateOutgoingShipmentEndpoint>
            .Create(dbContext.Object);

        await endpoint.HandleAsync(request, CancellationToken.None);

        shipment.StartPointKind.Should().Be(ShipmentStartPointKind.Brewery);
        shipment.StartBrewery.Should().Be(brewery);
        shipment.StartBreweryId.Should().Be(brewery.Id);
    }

    [Fact]
    public async Task HandleAsync_UnknownStartBreweryId_Returns404()
    {
        var (_, request, dbContext) = Arrange(OutgoingShipmentState.Created, []);

        request.Data.StartPointKind = ShipmentStartPointKind.Brewery;
        request.Data.StartBreweryId = Guid.NewGuid();

        var endpoint = EndpointBuilder<UpdateOutgoingShipmentRequest, UpdateOutgoingShipmentEndpoint>
            .Create(dbContext.Object);

        var act = async () => await endpoint.HandleAsync(request, CancellationToken.None);

        await act.Should().ThrowAsync<AleTrackException>()
            .Where(e => e.ErrorCode == ErrorCodes.NotfoundError);
    }

    [Fact]
    public async Task HandleAsync_StartPointChangedOnLoadedShipment_IsRejectedAsFrozenContent()
    {
        var brewery = BreweryBuilder.BuildEntity(name: "Svijany");
        var (_, request, dbContext) = Arrange(OutgoingShipmentState.Loaded, [brewery]);

        request.Data.State = OutgoingShipmentState.Loaded;
        request.Data.StartPointKind = ShipmentStartPointKind.Brewery;
        request.Data.StartBreweryId = brewery.PublicId;

        var endpoint = EndpointBuilder<UpdateOutgoingShipmentRequest, UpdateOutgoingShipmentEndpoint>
            .Create(dbContext.Object);

        var act = async () => await endpoint.HandleAsync(request, CancellationToken.None);

        await act.Should().ThrowAsync<AleTrackException>()
            .Where(e => e.ErrorCode == ErrorCodes.ShipmentContentFrozen);
    }

    [Fact]
    public void Validate_StartPointKindCompanyWithBreweryId_FailsValidation()
    {
        var dto = OutgoingShipmentBuilder.BuildUpdateDto();
        dto.StartPointKind = ShipmentStartPointKind.Company;
        dto.StartBreweryId = Guid.NewGuid();

        var result = new UpdateOutgoingShipmentDtoValidator().TestValidate(dto);

        result.ShouldHaveValidationErrorFor(d => d.StartBreweryId);
    }

    [Fact]
    public void Validate_StartPointKindBreweryWithoutBreweryId_FailsValidation()
    {
        var dto = OutgoingShipmentBuilder.BuildUpdateDto();
        dto.StartPointKind = ShipmentStartPointKind.Brewery;
        dto.StartBreweryId = null;

        var result = new UpdateOutgoingShipmentDtoValidator().TestValidate(dto);

        result.ShouldHaveValidationErrorFor(d => d.StartBreweryId);
    }

    /// <summary>
    /// A shipment in the given state with one order stop, plus a PUT that round-trips
    /// it unchanged — so each test changes exactly the one thing it is about. Drivers are
    /// left empty: the default driver ID generated by <see cref="OutgoingShipmentBuilder.BuildUpdateDto"/>
    /// does not exist in this mock and is irrelevant to what these tests check.
    /// </summary>
    private static (OutgoingShipment Shipment, UpdateOutgoingShipmentRequest Request, Mock<AleTrack.Infrastructure.Persistence.AleTrackDbContext> DbContext)
        Arrange(OutgoingShipmentState state, List<Brewery> breweries)
    {
        var shipmentId = Guid.NewGuid();
        var orderId = Guid.NewGuid();
        var client = ClientBuilder.BuildEntity(officialAddress: AddressBuilder.BuildEntity());
        var order = OrderBuilder.BuildEntity(publicId: orderId, client: client);

        var shipment = OutgoingShipmentBuilder.BuildEntity(publicId: shipmentId, state: state);
        shipment.Stops.Add(new OutgoingShipmentStop
        {
            Kind = OutgoingShipmentStopKind.Order,
            ClientOrder = order,
            Order = 1
        });

        var dbContext = AleTrackDbContextMockFactory.CreateMock(
            outgoingShipments: [shipment],
            orders: [order],
            breweries: breweries);
        dbContext.Setup(x => x.SaveChangesAsync(It.IsAny<CancellationToken>())).ReturnsAsync(1);

        var request = new UpdateOutgoingShipmentRequest
        {
            Id = shipmentId,
            Data = OutgoingShipmentBuilder.BuildUpdateDto(
                driverIds: [],
                clientOrderShipments: [new ClientOrderShipmentDto { ClientOrderId = orderId, Order = 1 }],
                state: state)
        };

        return (shipment, request, dbContext);
    }
}
