// <auto-generated />
using System;
using AleTrack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AleTrack.Migrations
{
    [DbContext(typeof(AleTrackDbContext))]
    partial class AleTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AleTrack.Entities.Brewery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("breweries", (string)null);
                });

            modelBuilder.Entity("AleTrack.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("AleTrack.Entities.DeliveryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount");

                    b.Property<long>("DeliveryStopId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delivery_stop_id");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryStopId");

                    b.HasIndex("ProductId");

                    b.ToTable("delivery_items", (string)null);
                });

            modelBuilder.Entity("AleTrack.Entities.DeliveryStop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("BreweryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("brewery_id");

                    b.Property<long>("DeliveryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delivery_id");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.HasKey("Id");

                    b.HasIndex("BreweryId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("delivery_stops", (string)null);
                });

            modelBuilder.Entity("AleTrack.Entities.Driver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("AleTrack.Entities.DriverAvailability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("DriverId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("From")
                        .HasColumnType("TEXT")
                        .HasColumnName("from");

                    b.Property<DateTime>("Until")
                        .HasColumnType("TEXT")
                        .HasColumnName("until");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("driver_availabilities", (string)null);
                });

            modelBuilder.Entity("AleTrack.Entities.InventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<long?>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("AleTrack.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("delivery_date");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("AleTrack.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount");

                    b.Property<long>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("AleTrack.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<float?>("AlcoholPercentage")
                        .HasColumnType("REAL")
                        .HasColumnName("alcohol_percentage");

                    b.Property<long>("BreweryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("brewery_id");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double?>("PackageSize")
                        .HasColumnType("REAL")
                        .HasColumnName("package_size");

                    b.Property<float?>("PlatoDegree")
                        .HasColumnType("REAL")
                        .HasColumnName("plato_degree");

                    b.Property<decimal>("PriceForUnitWithVat")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_for_unit_with_vat");

                    b.Property<decimal>("PriceForUnitWithoutVat")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_for_unit_without_vat");

                    b.Property<decimal>("PriceWithVat")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_with_vat");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("BreweryId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("AleTrack.Entities.ProductDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("VehicleId");

                    b.ToTable("product_deliveries", (string)null);
                });

            modelBuilder.Entity("AleTrack.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Password = "$2a$13$vSTwVilIMPc4b6AQEx6BAe.jKbwcLbBcUuaPZ6P.s23N36bB4MbFu",
                            PublicId = new Guid("5e58584b-76f1-4205-a5ab-9a37730db25b"),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("AleTrack.Entities.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Type = 0,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("AleTrack.Entities.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("REAL")
                        .HasColumnName("max_weight");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("public_id");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("product_delivery_drivers", b =>
                {
                    b.Property<long>("product_delivery_id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("driver_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("product_delivery_id", "driver_id");

                    b.HasIndex("driver_id");

                    b.ToTable("product_delivery_drivers", (string)null);
                });

            modelBuilder.Entity("AleTrack.Entities.Brewery", b =>
                {
                    b.OwnsOne("AleTrack.Entities.Address", "ContactAddress", b1 =>
                        {
                            b1.Property<long>("BreweryId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("contact_address_city");

                            b1.Property<int>("Country")
                                .HasColumnType("INTEGER")
                                .HasColumnName("contact_address_country");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("contact_address_street_name");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("contact_address_street_number");

                            b1.Property<string>("Zip")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("contact_address_zip");

                            b1.HasKey("BreweryId");

                            b1.ToTable("breweries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BreweryId");
                        });

                    b.OwnsOne("AleTrack.Entities.Address", "OfficialAddress", b1 =>
                        {
                            b1.Property<long>("BreweryId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("official_address_city");

                            b1.Property<int>("Country")
                                .HasColumnType("INTEGER")
                                .HasColumnName("official_address_country");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("official_address_street_name");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("official_address_street_number");

                            b1.Property<string>("Zip")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("official_address_zip");

                            b1.HasKey("BreweryId");

                            b1.ToTable("breweries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BreweryId");
                        });

                    b.Navigation("ContactAddress");

                    b.Navigation("OfficialAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("AleTrack.Entities.Client", b =>
                {
                    b.OwnsOne("AleTrack.Entities.Address", "ContactAddress", b1 =>
                        {
                            b1.Property<long>("ClientId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("contact_address_city");

                            b1.Property<int>("Country")
                                .HasColumnType("INTEGER")
                                .HasColumnName("contact_address_country");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("contact_address_street_name");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("contact_address_street_number");

                            b1.Property<string>("Zip")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("contact_address_zip");

                            b1.HasKey("ClientId");

                            b1.ToTable("clients", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.OwnsOne("AleTrack.Entities.Address", "OfficialAddress", b1 =>
                        {
                            b1.Property<long>("ClientId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("official_address_city");

                            b1.Property<int>("Country")
                                .HasColumnType("INTEGER")
                                .HasColumnName("official_address_country");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("official_address_street_name");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("official_address_street_number");

                            b1.Property<string>("Zip")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("official_address_zip");

                            b1.HasKey("ClientId");

                            b1.ToTable("clients", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("ContactAddress");

                    b.Navigation("OfficialAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("AleTrack.Entities.DeliveryItem", b =>
                {
                    b.HasOne("AleTrack.Entities.DeliveryStop", "DeliveryStop")
                        .WithMany("Items")
                        .HasForeignKey("DeliveryStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AleTrack.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeliveryStop");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AleTrack.Entities.DeliveryStop", b =>
                {
                    b.HasOne("AleTrack.Entities.Brewery", "Brewery")
                        .WithMany()
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AleTrack.Entities.ProductDelivery", "Delivery")
                        .WithMany("Stops")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brewery");

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("AleTrack.Entities.DriverAvailability", b =>
                {
                    b.HasOne("AleTrack.Entities.Driver", "Driver")
                        .WithMany("Availabilities")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("AleTrack.Entities.InventoryItem", b =>
                {
                    b.HasOne("AleTrack.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AleTrack.Entities.Order", b =>
                {
                    b.HasOne("AleTrack.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AleTrack.Entities.OrderItem", b =>
                {
                    b.HasOne("AleTrack.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AleTrack.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AleTrack.Entities.Product", b =>
                {
                    b.HasOne("AleTrack.Entities.Brewery", "Brewery")
                        .WithMany("Products")
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brewery");
                });

            modelBuilder.Entity("AleTrack.Entities.ProductDelivery", b =>
                {
                    b.HasOne("AleTrack.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AleTrack.Entities.UserRole", b =>
                {
                    b.HasOne("AleTrack.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("product_delivery_drivers", b =>
                {
                    b.HasOne("AleTrack.Entities.Driver", null)
                        .WithMany()
                        .HasForeignKey("driver_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_product_delivery_drivers_drivers_driver_id");

                    b.HasOne("AleTrack.Entities.ProductDelivery", null)
                        .WithMany()
                        .HasForeignKey("product_delivery_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_product_delivery_drivers_product_deliveries_product_delivery_id");
                });

            modelBuilder.Entity("AleTrack.Entities.Brewery", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AleTrack.Entities.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AleTrack.Entities.DeliveryStop", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AleTrack.Entities.Driver", b =>
                {
                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("AleTrack.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("AleTrack.Entities.ProductDelivery", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("AleTrack.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
